### ISSUE TITLE
Add manual process kill exceptions

### ISSUE THREAD

**Issue by ion-storm** [bmrf/tron#10]
Can we add manual settings to not kill certain processes for Terminal server/remote admin sessions?  It would be nice to add a flag -e teamviewer.exe screenconnect.exe kaseya.exe Mass killing of processes on a terminal server can be dangerous especially with a few hundred users connected. 
Thanks

**Comment by vocatus** [comment]
Right now there are two utilities that kill processes; /u/cuddlychops06's "ProcessKiller.exe" and RogueKiller. Ping /u/cuddlychops06 on Reddit and see if he can add white-list support (he's been working on adding support for a "whitelist.txt" or similar functionality). 

As far as RogueKiller, we haven't found a way to stop it from killing remote sessions yet. :-/ The soultion right now is to either delete its .exe, or just comment out or delete that block in the script ([lines 1042-1049 in the v6.1.0 code](https://github.com/bmrf/tron/blob/610a0082a97db2c24dcd98e8da5a59a5c696dd15/tron.bat#L1042-L1049)).

**Comment by vocatus** [comment]
Resolved with the inclusion of ProcessKiller's whitelist support.
