### ISSUE TITLE
Add some more

### ISSUE THREAD

**Issue by Tigzy** [bmrf/tron#101]
RogueKiller (CMD version?), Ucheck for software updates automation.

**Comment by bknickelbine** [comment]
Tigzy - Don't RogueKiller and UCheck require a technician license to enable command-line invocation?

**Comment by Tigzy** [comment]
Not necessarily for RogueKiller: http://www.adlice.com/documentation/roguekillercmd/documentation/
Just run: RogueKillerCMD.exe -scan -dont_ask
It will perform scan/removal (with PUP/PUM unchecked by default)

For UCheck, You are right CMD version requires a Tech license...

**Comment by vocatus** [comment]
Interesting, I had not heard of UCheck. I'll take a look at it. 

As far as RogueKiller, quite a while ago they purposefully broke/removed CLI functionality to force purchase of a technician license for automation. Are you sure those commands work on the current free version?

**Comment by Tigzy** [comment]
Yes, we have limited the CLI interface but for a basic usage it can be used with free version.

**Comment by vocatus** [comment]
@Tigzy OK, I'll give it a shot, thank-you.

**Comment by vocatus** [comment]
@Tigzy it looks like RogueKiller will only scan, but not remove things from the command-line, so I'll have to decline adding it for now. Let me know if it supports automatic removal from the CLI in the future.

**Comment by Tigzy** [comment]
Hey, actually doing: 
RogueKillerCMD.exe -scan -dont_ask
does scan AND remove infections (except PUP/PUM, because it could be dangerous not reviewing those items before removal)
