### ISSUE TITLE
[Suggestion] Add flags for specific bloat removal, separate

### ISSUE THREAD

**Issue by kronflux** [bmrf/tron#111]
Two ideas, which would drastically improve usefulness in regards to new computer setups, as opposed to only repair situations.

1) Add flags to run specific sections of bloat removal(for example, I wouldn't need to run toolbar removals, since it's a brand new unit, and in 99.99999999% of cases, there are no included toolbars. In fact, toolbars on Windows 10 are rare in general.
I would, however, benefit from the Metro removals and the GUID removals(for the OEM included software)

2) Separate software into separate lists - One for general and one for OEM included software. Reasons are the same as above - a fresh HP or Dell unit(for example) would have some OEM garbage on it, but would not have any general unwanted software.
Granted, this would take some time, and community involvement in identifying what's what. But in the long run, would make an excellent addition to part 1 of this suggestion.

**Comment by WolfX2** [comment]
What a great idea!

**Comment by vocatus** [comment]
commenting to let you know I haven't ignored or forgotten this, just been busy. Let me think it over.

**Comment by vocatus** [comment]
@kronflux I've busy with other things lately (as evidenced by slower than normal Tron releases), but would you be willing to take a stab at breaking out some of the basic OEM sections from `programs_to_target_by_GUID.txt`? Just like `programs_to_target_by_GUID_dell.txt`, `programs_to_target_by_GUID_acer.txt` etc?

**Comment by kronflux** [comment]
Definitely, I'll take a look at doing that later today.
I did realize there's a slight issue with the entire idea however - Many of the programs that come along with units are not branded by the manufacturer(for example, Cyberlink products). The purpose of my idea was to speed up new computer removals, but with situations like that, the only thing we'd speed up is if one opted to only remove brand specific software.

That being said, this could still be a useful feature for some, and I believe it's worth doing anyway.

Long term, what might be a better idea is to have the OEM specific removals be completely optional, and add common software into those removals(programs_to_target_by_GUID_oem-general.txt for example)
Use the full list for standard removals, which still would include the OEM specific stuff, and use separate lists for OEM only removals, which would not include the various malware/junkware/other stuff..

Sufficed to say, it needs further thought.

**Comment by kronflux** [comment]
I'd say lets close this issue for now, as it's going to need some planning and re-thinking - especially where it's the only active issue.

Next time I have some time, I'll give it some further thought and try and figure out the best way to go about something along these lines.

@vocatus

**Comment by vocatus** [comment]
@kronflux OK, sounds good. Thanks for the thoughts. I'll close it out.
