### ISSUE TITLE
[BUG] Windows CBS folder is not cleaned with TempFileCleanup.bat

### ISSUE THREAD

**Issue by jonasjovaisas** [bmrf/tron#122]
https://github.com/bmrf/tron/blob/03b60079daf62334b160298cc05537a9f5171ce5/resources/stage_1_tempclean/tempfilecleanup/TempFileCleanup.bat#L233-L235

In file **TempFileCleanup.bat** in lines 233-235 the CBS logs cleanup is described.

In line 234 it states, that it looks for Vista OS or newer (without Microsoft in OS name) and deletes CBS folder contents.
However line 235 checks for name "server" in the OS name. As it is stated in the comments text, perhaps it should check for winver **not containing word Microsoft**?

On Windows 10 Pro C:\Windows\Logs\CBS folder was not cleaned.

**Comment by vocatus** [comment]
Thanks for the clear and concise bug report. I don't know how that was in there so long... 

Pushed the fix to Github and it will go out in the next Tron version as well.

**Comment by jonasjovaisas** [comment]
You're most certainly welcome. It's the least I can do in appreciation
after using your tool several times.

Please keep up the great work, vocatus!
