### ISSUE TITLE
Stage5: Patch - Adobe - plugin filenames

### ISSUE THREAD

**Issue by Diskmaster** [bmrf/tron#131]
The filenames that are shipped with the current release of tron don't match the ones in resources\stage_5_patch\adobe\flash_player\Adobe Flash Player Installer.bat

git expects install_flash_player_26*, release v10.4.8 expects install_flash_player_27* but has 28 in the filename, and thus probably won't install correctly.

Reference: https://github.com/bmrf/tron/blob/c371ebd98bb08f8b6787f5bcc304ee1070cf5d5c/resources/stage_5_patch/adobe/flash_player/Adobe%20Flash%20Player%20Installer.bat#L72-L85

**Comment by vocatus** [comment]
Good find, thank-you. I'll fix and it will go out in the next version.
