### ISSUE TITLE
[Feature request] Add Event Log repair

### ISSUE THREAD

**Issue by qwertychouskie** [bmrf/tron#133]
As detailed [here](https://www.bleepingcomputer.com/forums/t/671540/januaryfebruary-security-patches-fail-configuring-at-98-with-0x80070057-error/), sometimes the keys in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\WINEVT\Publishers\` can get corrupted/deleted.  It would be nice if Tron could automatically fix these types of issues.

**Comment by vocatus** [comment]
Hi @qwertychouskie , thanks for the suggestion, sounds like something that would be a good fit for Tron. Can you explain a little more? From the thread you linked it looks like some data needed to be re-added to the registry, is that specific to your system or does it apply to all systems?

**Comment by qwertychouskie** [comment]
Honestly, I don't know much other than that that one key was missing on my system.

**Comment by kronflux** [comment]
I'm not sure how common this is(ie: common enough it would make sense to add) but I suppose a simple detection could easily check to make sure the data matches.

I've been repairing Windows systems professionally for many years, and have never run into this.

To clarify, the data is identical across Windows systems, as they're simply references to a couple print service related dll's.
Why they export in hex is beyond me, but basically both entries references in the article are pointing to "%SystemRoot%\system32\ntprint.dll"

The only thing I don't see on multiple systems is the "Enable" DWORD value, but I imagine that refers specifically to something print server related.

To generalize the issue, ie: different sub-keys in the Publishers key, there are far too many to reasonably/realistically check all of them, especially seeing as how, again, this isn't all that common.
As far as I can tell, the majority are the same across systems though. Hard to say if there are any ones unique to each system.

**Comment by vocatus** [comment]
Since this seems to be a fairly niche issue, I'm going to close for now. If it ends up being a more common complaint I'll look at adding it in. Thanks.
