### ISSUE TITLE
Add switches for disabling TempFileCleanup.bat, SFC and the Repair File Extensions Stage

### ISSUE THREAD

**Issue by Kaos-Industries** [bmrf/tron#134]
Hey there.

Firstly, thanks to vocatus and the community for a great tool. I've spent the last day or so going through it in detail and it looks incredibly promising. However, I've since noticed a few things I'd like to prevent from running; these are the System File Checker, the execution of TempFileCleanup.bat, and the Repair File Extensions step.

Looking into the source code of TempFileCleanup.bat tells me that some things it's doing are a little too aggressive for my liking, from deleting browser temp files and useful logs, to deleting default Windows 7 backgrounds, to emptying search caches and the Recycle Bin.

Likewise with Repairing File Extensions; I really don't want to undo years of assigning extensions to certain programs by having everything restored to factory settings, especially when I'm certain nothing about the extensions are broken. This again feels more aggressive than it needs to be, especially without a switch to disable the behaviour.

**I've been unable to find switches in the documentation to disable the above steps. Is it possible that these can be added to Tron?** 

For now, I'm making do with editing the batch files to remove/alter the respective stages directly, but this is a short-term solution and it would be really great to be maintain a single copy of Tron and use command-line switches to disable any of the above behaviours as needed. 

Thank you.

**Comment by qwertychouskie** [comment]
Why do you want to disable SFC?  SFC should never hurt anything/change settings/etc.

**Comment by vocatus** [comment]
Hi @Kaos-Industries, thanks for the thoughts.

For now I'm going to leave everything as-is, since Tron is intended for system rescue and not as a regular maintenance tool. In a rescue environment it makes more sense to reset file extensions (frequently hijacked), run SFC, and wipe cache/recycle bin/etc. 

Of course you're welcome to tweak your copy of Tron so that it doesn't perform those actions; crack open any of the scripts and disable or delete whatever you don't like.

**Comment by qwertychouskie** [comment]
Tron is useful for more than just rescuing system though, it is good for any Windows system that needs a performance boost from a good cleaning (a.k.a. almost all of them. ;)
