### ISSUE TITLE
Skip proprietary programs when running 

### ISSUE THREAD

**Issue by tsmock** [bmrf/tron#135]
I'd like to run only the bits that don't want a commercial license.

Right now I can get most of it through the use of the following switches: 
-sm, -sk, -ss (basically, -sa)

What this patch[1] currently does:
Add a switch for SKIP_PROPRIETARY -- might want to change to SKIP_NONCOMMERCIAL
When SKIP_PROPRIETARY is yes, run the built in windows defragger, skip the antivirus scans, and (when re-enabled) skip CCleaner.

What I'm trying to do: add the ability to skip programs that want a license to run in a commercial setting while still (in some cases) getting things done.

Before I get much further into the weeds, I'd like to know if this is something that would be accepted.

Things missing in patch [1]:

- [ ] Ability to re-enable programs that you have a license for
- [ ] Many, many programs that probably want a commercial license don't have the surrounding if's
- [ ] Indicate that flag is on a best-effort basis
- [ ] Antivirus like Clam AV [3] that can run with this flag set

Stages that probably don't have to be changed:
- [ ] TempClean (changed in patch)
- [ ] De-bloat
- [ ] Patch
- [ ] Optimize (changed in patch)
- [ ] Wrap-up

Stages that probably have to be changed:
- [ ] Prep (I've done some work in the patch)
- [ ] Disinfect (changed in patch, needs more work)
- [ ] Repair (telemetry removal?)

[1] [https://github.com/tsmock/tron/tree/proprietary](https://github.com/tsmock/tron/tree/proprietary)
[2] [https://www.reddit.com/r/TronScript/comments/3dicb6/flag_that_doesnt_include_licensed_programs/](https://www.reddit.com/r/TronScript/comments/3dicb6/flag_that_doesnt_include_licensed_programs/)
[3] [https://www.clamav.net/](https://www.clamav.net/)

**Comment by vocatus** [comment]
Hi @tsmock, 

I do appreciate the idea behind this, and partly agree, however since Tron relies so heavily on many 3rd-party tools, and disabling their use would make Tron significantly less effective (if not entirely), I'm going to reject this for now. You're welcome to fork the Tron repo though and offer a version with that switch included, I'm sure there are a few other people who would like that functionality.

**Comment by dimqua** [comment]
Many thanks for your work @tsmock.

>Ability to re-enable programs that you have a license for

You may want to skip running proprietary software (non-[free](https://en.wikipedia.org/wiki/Free_software)), since [it can't be trustful](https://www.gnu.org/proprietary/proprietary.en.html). To me this is the only reason to do so.
