### ISSUE TITLE
Command-line Arguments not utilized in unsupported system versions

### ISSUE THREAD

**Issue by justinhachemeister** [bmrf/tron#142]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem with the latest version.
    * Attempted to debug the issue.
    * Checked the documentation to see if a solution already exists.
    * Checked that your issue is not already filed.

### Description

Tried to run this on a SQL Server machine and received the error:

```markdown
Tron does not support "%WIN_VER%" (yet).`
If you want to override and run anyway, re-run
Tron from the command-line with the -dev flag.
```
Ran Tron with `-dev` but the message persists.

### Steps to Reproduce

1. Run Tron on unsupported system version.
2. Pass `-dev` to Tron.
3. Message about Tron not supporting system version persists.

**Expected behavior:** [What you expect to happen]

Applying the `-dev` flag should be respected to override the supported version if the help message provides this method as a solution.

**Actual behavior:** [What actually happens]

Applying the `-dev` flag is not respected, and works as though it had not been provided.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

You can get this information from the library being used that is causing the issue. Also, please include the OS and what version of the OS you're running.

Version Information:

```batch
set SCRIPT_VERSION=1.1.2
set SCRIPT_DATE=2018-03-15
```
Operating System:
Windows Server 2016

### Additional Information

> Any additional information, configuration or data that might be necessary to reproduce the issue.

Additional settings are not being respected because the `prerun_checks_and_tasks` function is called before `parse_cmdline_args`.

I am submitting a pull request, but wanted an issue to tag it with.

**Comment by vocatus** [comment]
Closing as resolved, thanks for the excellent write-up and good fix.
