### ISSUE TITLE
Remove "Tron Quotes.txt" from distribution packages.

### ISSUE THREAD

**Issue by ellisgeek** [bmrf/tron#15]
In the most recent tron builds there is a Text file containing quotes from reddit users that are completely unprofessional. I keep a copy of tron on a flash drive and recently updated it. Today we were training a new hire and some one opened the file only to be greeted by a fair number of Inappropriate quotes.

**Comment by vocatus** [comment]
Keep in mind that Tron is a personal project and provided completely for free, and it's very easy to just delete the quotes file before distributing the utility to your techs.

I'll give your suggestion some consideration, but not promising anything at the moment.
