### ISSUE TITLE
Breaking Windows search for settings

### ISSUE THREAD

**Issue by orrinwitt** [bmrf/tron#157]
I use tron when i work on computers for work and I'm running into a serious issue i don't know how to fix: it's breaking the windows search. The search still technically works, but I can no longer search any settings, some of which are hard to find without being able to use the search. I'm not sure where it's getting broken, but it's causing some unhappy customers for me lately!

**Comment by AndrewSav** [comment]
This is also affecting me. For me suggestion in [this thread](https://www.reddit.com/r/TronScript/comments/a4lm5n/any_fix_for_strat_menusettings_not_being/) fixed the issue. But would be nice if it does not happen in the first place.

**Comment by vocatus** [comment]
One of the issues is I'm having trouble tracking down exactly where in the script this is happening. Is there any chance @AndrewSav and @orrinwitt you could run just single stages in a VM and see which stage it's  breaking in?

**Comment by orrinwitt** [comment]
I haven't done a stage by stage test, but I think it's in the telemetry removal stage, because it does it even if I skip debloat. Hope that helps some?

**Comment by orrinwitt** [comment]
Also, @vocatus , thank you for all your hard work on this script!

**Comment by vocatus** [comment]
Okay @orrinwitt and @AndrewSav , I ran v10.7.4 Stage 4 (repair + telemetry removal) on a fresh Win10 VM running 1709, and Search in the Start Menu still worked. I'll install all updates and try again. If either of you could spare time to test the other stages individually and see if it breaks search that'd be awesome.

**Comment by AndrewSav** [comment]
@vocatus just to be 100% sure we are on the same page. If you type "env" to the start, you are supposed to see this:
![2019-01-29_18-36-46](https://user-images.githubusercontent.com/658865/51886521-0affb280-23f5-11e9-82f2-e1bb9a95173a.png)

Can you check and confirm that you are seeing this, as opposed to nothing displayed?

**Comment by orrinwitt** [comment]
It bears mentioning that search is not completely broken. For instance, if you type in settings, settings will come up in the results, but if you type in updates, "Check for Updates" will not come up. I'll have to do some more testing to see exactly what, but not being able to search within settings is the major rub.

**Comment by vocatus** [comment]
@AndrewSav just finished Stage 0 as well, nothing broken. But when I ran Stage 1 (tempclean), search started only working "kind of." it would still show folders, but the term I'd been using to test, "control panel," returned nothing. I'll dig into Stage 1 and see if I can't figure out what's causing it.

**Comment by AndrewSav** [comment]
@vocatus yep, that's it!

**Comment by orrinwitt** [comment]
I'll be really glad when we squash this bug. Some of the Windows 10 settings are difficult to navigate to without search, and it turns a two-step process (type, click) into a six-step process (click x6). 
On a side note, I think one time I had this and a major Windows feature update restored it ¯\_(ツ)_/¯

**Comment by vocatus** [comment]
> 
> 
> I'll be really glad when we squash this bug. Some of the Windows 10 settings are difficult to navigate to without search, and it turns a two-step process (type, click) into a six-step process (click x6).
> On a side note, I think one time I had this and a major Windows feature update restored it ¯_(ツ)_/¯

It doesn't personally affect me since I use Classic Shell to have an old school menu, but I know it causes a major pain point for a lot of people. My win10 test VM is just installing a ton of updates and once it's done I'll snapshot it and start testing. Hoping to have it resolved by the end of today.

**Comment by vocatus** [comment]
@orrinwitt @AndrewSav I think I've found the culprit; search is broken immediately after running CCleaner. Can you test on your system or a VM and see if you can replicate it?

**Comment by vocatus** [comment]
@AndrewSav @orrinwitt fixed it. CCleaner's copy of `winapp2.ini`  had a clearing command that broke search which was fixed in a new version. OR it could've been that the file was in Unix line-ending format (CR) instead of Windows' (CR LF)...no idea how that happened. Updating to the latest version and switching the encoding seems to have fixed it, Start Menu search still works after a full Tron run. I'll close this out and push out the fixed version.

**Comment by orrinwitt** [comment]
Awesome! Thanks @vocatus !
