### ISSUE TITLE
stage_2_de-bloat cuts names short from programs_to_target_by_name

### ISSUE THREAD

**Issue by AndrewSav** [bmrf/tron#158]
`for /f` by default uses `tokens=1` and `delims=<tab><space>`

This means that in [this loop](https://github.com/bmrf/tron/blob/d6f1d69c676f02a557f3f1c0e270fc776c02a129/resources/stage_2_de-bloat/stage_2_de-bloat.bat#L220) a name, that has whitespaces, like [Big Fish Games: Game Manager](https://github.com/bmrf/tron/blob/d6f1d69c676f02a557f3f1c0e270fc776c02a129/resources/stage_2_de-bloat/oem/programs_to_target_by_name.txt#L71) will result in `%%i` to be equal `Big` which is not desired / intented. The command that will get run as the result will be `"wmic.exe"  product where "name like 'Big'" uninstall /nointeractive`, which is not effective.

This is on Windows 10 with all the latest Windows Updates as of the time of writing.

For a fix suggest substituting `for /f %%i` with `for /f "delims=" %%i` in that loop. Not, tested use at your own risk.

**Comment by AndrewSav** [comment]
As a side note, this single loop takes several hours, even if non of the applications are present. It feels like a huge waste of time. I would appreciate a key to turn it off _just for this particular loop_ , the guid ones are reasonably fast. Of course I can always substitute an empty `programs_to_target_by_name.txt` but a key would would be neater.

**Comment by vocatus** [comment]
Finally got around to looking at this and testing your solution, and it worked. Good catch and thanks for the fix. It'll go out in the next release.
