### ISSUE TITLE
[REQUEST] A script to remove unused drivers

### ISSUE THREAD

**Issue by ptrkhh** [bmrf/tron#161]
For example, if you just swapped out an AMD Radeon card for an Nvidia GeForce card, the script would detect that there is a driver that's currently unused by any hardware, and automatically remove it.

Check out the script here: https://theitbros.com/remove-old-unused-drivers-using-powershell/

This probably better configured off by default, since it may remove printer drivers when its powered off for example. Alternatively, it could also ask for confirmation for every driver removal beforehand.

**Comment by vocatus** [comment]
Hi @ptrkhh , I'll take a look at it and see if it's a good fit for Tron. Thanks.

**Comment by ravaan** [comment]
This is a great idea. 

Though, prompting for each driver would be too much and also in many cases people won't know/won't be able to figure out what driver specifically does and may tend to accept it's removal (this is considering they are properly going through the whole script). 

If we can figure out when the driver was last used/when that hardware was last plugged in and then set a threshold say 6 months (give an option to adjust the threshold) and remove all drivers not used in that time period. This is one approach.

All said, I still think there should be a smarter way to handle this.

Great Idea

**Comment by vocatus** [comment]
Hi @ptrkhh , after testing and reviewing, I think I'm going to leave this out of Tron for the time being. Reasoning being that while driver removal is a good idea (and often saves a ton of space), it's a little more prone to causing errors than I'm comfortable with for the average user, so I'll leave this in the "up to the discretion of the tech" category. Thanks for the great suggestion.
