### ISSUE TITLE
[REQUEST] Adblock via hosts file

### ISSUE THREAD

**Issue by ptrkhh** [bmrf/tron#162]
The hosts file is located at C:\Windows\System32\drivers\etc\hosts (no file extension).

This is a good source for the hosts file in my opinion https://github.com/StevenBlack/hosts

**Comment by vocatus** [comment]
Hi @ptrkhh, 

Thanks for the suggestion. Unfortunately I don't think this is a good fit for the Tron project for the following reasons:
1. Adblocking via hosts file is very ineffective as servers serving ads change IP address and domain name frequently
2. It goes against the [development philosophy of Tron](https://www.reddit.com/r/TronScript/comments/2rr0l6/qa_time_thoughts_on_my_goalsphilosophy_and_how/), #2 of which is "restrict system tweaks and leave everything as close to stock as possible."
