### ISSUE TITLE
[REQUEST] Integrate Wufuc on Windows 7 - 8.1 if running on an unsupported hardware

### ISSUE THREAD

**Issue by ptrkhh** [bmrf/tron#164]
This is wufuc: https://github.com/zeffy/wufuc

Basically Microsoft sets an artificial limitation on Windows 7 and 8 that blocks some features on newer, or very old processors. Wufuc is designed to fix that problem.

Admittedly this is probably a very niche scenario, and I don't know how easy/legal it is to integrate that program here.

**Comment by vocatus** [comment]
Hi @ptrkhh , thanks for the suggestion. I agree this is a useful fix, however as it's fairly niche and I try to keep Tron as trim as possible, I'm going to hold off including this for now.
