### ISSUE TITLE
Malwarebytes Command Line Parameters

### ISSUE THREAD

**Issue by spinjector** [bmrf/tron#165]
Hello, I just discovered Tron and reading through the stages, noticed it says MBAM has no command line switches, but it does. Thing is: after it's installed, commands aren't handled through mbam.exe, but another file called mbamapi.exe. 

Check the admin guide PDF here: https://support.malwarebytes.com/docs/DOC-1725, especially pages 9 and 33. The exe installer does have the switches, but I'm not sure about the msi.

We're going through a big malware remediation after Trickbot gave us a black eye, and I've been playing with mbamapi.exe to package it up in a Active Directory domain policy. But note: we have the corporate version with a license, I don't know to what extent the api is implemented in the freeware version.

There is also this page which says mbam.exe does have some basic switches, but I haven't tried/verified any of this: https://www.howtoguides.org/run-malwarebytes-from-command-prompt.

I should note that I originally started trying to script everything with a VBS file, with each .Run command line set to "1" for normal-window mode, and I quickly discovered each command opens a new window, so suddenly it looked like I won a game of Solitaire on Windows 98 with all the windows suddenly opening, lol.

So I switched it all to a CMD file instead, but then discovered mbamapi.exe runs silently, with no status message or anything. No word yet if there's a /verbose switch to make it respond with any text or even an error code. I just thought of testing that over the weekend, and I haven't gotten to it yet. But again...all this might be completely moot in the freeware version.

**Comment by vocatus** [comment]
Hi @spinjector , thanks for the info, I actually didn't know about `mbamapi.exe`. However, Malwarebytes not scanning is a [conscious decision](https://www.reddit.com/r/TronScript/wiki/index#wiki_1._why_doesn.27t_malwarebyte.27s_auto-scan.3F) to respect the wishes of Malwarebytes (the company). That link goes to Tron's CQ which answers some common questions about Tron.
