### ISSUE TITLE
-a and -asm cannot be used together

### ISSUE THREAD

**Issue by dcohen613** [bmrf/tron#166]
In the README, you state the following:

> - All switches are optional and can be used simultaneously.
> - -asm Automatically reboot to Safe Mode (**must be used with -a**, otherwise ignored)

However, when using the flags -a and -asm together, I get the following error:

> ERROR: You cannot use -a and -asm together. Pick one or the other.

These two scenarios are conflicting. Either the readme needs to be updated, or the code needs to allow both flags.

**Comment by vocatus** [comment]
Hi @dcohen613 , good find, thanks. I've updated the documentation to correctly reflect use of the `-a` and `-asm` switches.
