### ISSUE TITLE
stage_0_prep\log_tools\siv\siv64x.exe

### ISSUE THREAD

**Issue by mnestroy** [bmrf/tron#168]
![image](https://user-images.githubusercontent.com/10452210/64288154-f9503180-cf26-11e9-8cb3-da9e58f2b958.png)

**Comment by mnestroy** [comment]
Ignore, I didn't read the giant warning to not download from github :(

**Comment by vocatus** [comment]
Thanks for closing it out. Don't worry, we've all been there haha.
