### ISSUE TITLE
Stuck on stage 3

### ISSUE THREAD

**Issue by Pigeoncraft** [bmrf/tron#17]
So I just tried this out today and it seems like it skipped the first 2 stages and now its stuck on stage 3

    The system cannot find the path specified.
    The system cannot find the path specified.
    The system cannot find the path specified.
    The system cannot find the path specified.
    The system cannot find the file specified.
    2015-06-29 20:08:18.16 ! Incomplete run detected. Resuming at stage_3_disinfect using flags "0"...
    The system cannot find the drive specified.
                          Disk space reclaimed:       0 MB *
                          Logfile: C:\Logs\tron\tron.log

     * If you see negative disk space don't panic. Due to how some of Tron's
       functions work, actual disk space reclaimed will not be visible until
                          Disk space reclaimed:       0 MB *
                          Logfile: C:\Logs\tron\tron.log

     * If you see negative disk space don't panic. Due to how some of Tron's
       functions work, actual disk space reclaimed will not be visible until
                          Disk space reclaimed:       0 MB *
                          Logfile: C:\Logs\tron\tron.log

     * If you see negative disk space don't panic. Due to how some of Tron's
       functions work, actual disk space reclaimed will not be visible until

And it just continues with that.
If you need more info let me know.

**Comment by vocatus** [comment]
Hey Pigeoncraft, I saw you closed the issue, did you get it figured out?

**Comment by Pigeoncraft** [comment]
Yep Working great. I renamed the stage 3 folder by accident so it caused an error making the script close. When I started it back up it was trying to resume but couldn't find the stage 3 folder.

Thanks for checking in. And keep up the nice work!
