### ISSUE TITLE
Globe icon "no internet"... except there is

### ISSUE THREAD

**Issue by orrinwitt** [bmrf/tron#171]
I've got another one for you, @vocatus : 
I'm getting the globe icon where my lan icon should be. Mouseover message says "Network, No internet access", except there is internet access. I'm getting this on both of my computers, one with a fresh install of Windows 10, and the other is an older install that just started doing it. 
Both started doing it after running Tron 10.8.6
The reason I think it might be related to Tron is that stuff from the Microsoft store won't work. My daughter plays that stupid Roblox game, and it will just sit there and say "trying to connect". Also, when trying to browse the Microsoft Store, it constantly comes up with a "Can't connect to the internet" message.
I think it may be related to a Microsoft telemetry thing that gets disabled during Tron.
I know I'm usually no help when it comes to providing more information, but if you tell me what you need and how to get it, I'll be happy to try.

**Comment by orrinwitt** [comment]
small update: I got it to go away on the fresh install computer by uninstalling the driver from device manager, then letting it reinstall. But on the other computer, it seems to have no effect. I still tend to think it has something to do with something in the Windows telemetry being blocked.

**Comment by vocatus** [comment]
Hmmm. I thought I'd fixed this many versions ago. It is related to one of the telemetry servers that gets blocked. It can't connect to the server Microsoft set up to respond to that checker so it thinks you're not online even though you are. I'm not sure which specific server is the one that affects the connectivity check.
