### ISSUE TITLE
A handful of questions about tailoring Tron to my needs

### ISSUE THREAD

**Issue by fabiorfreitas** [bmrf/tron#174]
Hi, I've just ran Tron again and it was awesome as always

However, I'd like some help tailoring it to my future needs as I wish to avoid certain behaviours from it.
As I'm writing this, I'm going through Readme.md and trying to figure out by myself as much as I can, so the following questions are the parts I couldn't solve alone:

1- My HDD is not on the smartctldb. I've already submitted it to them, but perhaps there could be an option to override this, which made Tron skip Defrag for my run;

2- Rkill remove a registry entry that was created by SysInternals' Process Explorer to replace task manager. Stupid me didn't think to keep the .reg file rkill generated, didn't think I would write this. Anyway, how do I add this as an exception?

3- I don't want Tron to touch my browsers. Is setting anything with Chrome/Firefox/Mozzila in it to false on ccleaner.ini and bleachbit.ini enough?
3.1- I also don't want to lose recent items stuff from explorer and from ClassicStartMenu. Not sure if this is also on ccleaner and bleachbit or if its related to temp files or windows event logs;

4- Tron somehow disables Prey Anthitheft. I think it might be related to deleting Prey.pid from Temp, but there are a few other ocurrences of "Prey" in the log, so I'm not sure. How to circunvent it? (The other ocurrences are a scan of Prey service and this one: "Performing miscellaneous checks:* Reparse Point/Junctions Found (Most likely legitimate)!* C:\WINDOWS\Prey\current => C:\Windows\Prey\versions\1.9.2 [Dir]");

5- I also would like Tron not to modify UAC settings (I don't use this resource), but I have absolutely no clue as to what changing this. Perhaps its DISM?

OTHER:

a)Is there a way to restore the stuff I lost (item 3)? For browsers, I'm pretty sure that Tron wouldn't make backups, but I have some (suboptimal) ways to get that data again. What about the Windows stuff?

b)All of the stuff above is probably done by editing the appropriate batch files. Is there a way that I can write my own batch file to automatically do all these patches everytime I download a new version of Tron? Like something I could put in the master directory and it would call the necessary files, find the text and then replace it with what I need. Even better if there is a way to get a confirmation if the strings were indeed found, as they might not be present in future editions of Tron;

c) It has been perhaps 12h since I've ran Tron and I've got four times an error message 0xc0000142 for SetAPM.exe, which I've never seen before. Not sure if its related, but thought I'd better report it.

All in all, even though I should have prepared better with browser stuff, I'm satisfied with the results, the help I ask is because I intend to use it a lot in the future!

PS: I've choosen not to include the entirety of my logs here as they probably contain some info I shouldn't be posting carelessly, but I will provide them as requested.

Thank you a lot!

**Comment by vocatus** [comment]
Closing due to thread discussion on reddit.
