### ISSUE TITLE
PS1 script to EXE running Tron exits on VSS Purge

### ISSUE THREAD

**Issue by WaLLy3K** [bmrf/tron#177]
Hi vocatus, I have a bit of a weird issue to throw at you and interested in any input you can provide!

I have a .PS1 script I've converted to an EXE using [PS2EXE-GUI](https://gallery.technet.microsoft.com/scriptcenter/PS2EXE-GUI-Convert-e7cb69d5), which tailors PC servicing to my needs.

```
$desktop = [Environment]::GetFolderPath("Desktop")
Start-Process -FilePath "$desktop\tron\resources\stage_0_prep\stage_0_prep.bat" -NoNewWindow
pause
```

In trying to figure this out, I've found that if you save that as a PS1 file and convert that to an EXE, Tron will quit without warning [when this line is run](https://github.com/bmrf/tron/blob/7639383838650322799be9920ca23737694acec8/resources/stage_0_prep/stage_0_prep.bat#L336). (Make sure to untick 'compile a graphic windows program' and tick require admin rights when converting)

I've attempted to get some output from these commands by getting them to write directly from a file, but I get nothing I can use to figure out why this is happening.

Thanks

**Comment by vocatus** [comment]
Hmm, I don't have experience with converting PS1 scripts to .exe, but a couple questions or things to look at:

1. does it happen when just running the PS1 script vs. running the compiled .exe?

2. Is it possibly choking on one of the special characters in the command? e.g. `>` , `%` , `&` 

3. What does `c:\logs\tron\tron.log` say?

**Comment by freeload101** [comment]
this is what I use :


#TRONSCRIPT !
goto https://bmrf.org/repos/tron/ and get the filename of the exe and replace the file name in the url below

#TRONSCRIPT  NO AV !
goto https://bmrf.org/repos/tron/ and get the filename of the exe and replace the file name in the url below

powershell -NoP -NonI -W Hidden  -Exec Bypass "IEX (New-Object System.Net.WebClient).DownloadFile('https://www.rmccurdy.com/tronscript.exe',\"%userprofile%\desktop\tron.exe\"); Start-Process \"%userprofile%\desktop\tron.exe\" -ArgumentList \"-o%userprofile%\desktop\" -Wait ;Start-Process \"%userprofile%\desktop\tron\tron.bat\" -ArgumentList \"-a   -sa -sd\""


# full tronscript RUNS AV !
powershell -NoP -NonI -W Hidden  -Exec Bypass "IEX (New-Object System.Net.WebClient).DownloadFile('https://www.rmccurdy.com/tronscript.exe',\"%userprofile%\desktop\tron.exe\"); Start-Process \"%userprofile%\desktop\tron.exe\" -ArgumentList \"-o%userprofile%\desktop\" -Wait ;Start-Process \"%userprofile%\desktop\tron\tron.bat\""

**Comment by freeload101** [comment]
markup mangled my paste
reference:
https://rmccurdy.com/.scripts/fu.txt

**Comment by WaLLy3K** [comment]
> 1. does it happen when just running the PS1 script vs. running the compiled .exe?

I can't recall, I'll need to look into this - but I don't think it did!

> What does c:\logs\tron\tron.log say

Nothing, because the output from [that line](https://github.com/bmrf/tron/blob/7639383838650322799be9920ca23737694acec8/resources/stage_0_prep/stage_0_prep.bat#L336) is silenced.

> It's not particularly clear why are you converting a power shell script to an executable that just doesn't make any sense. what's the problem you're trying to solve with using an executable instead of just using PowerShell?

The broad stroke as I mentioned was "*which tailors PC servicing to my needs*". You can't just double click on a PS1 script (as that will by default just open up Notepad), and there's a few things I like to do before Tron runs, such as get the hard drive health output from Hard Drive Sentinel in a a very "fire and forget for a while" manner.

I just wanted to touch base on the thread since I've been inactive, but I'll get more info for you as soon as I can @vocatus :)

**Comment by WaLLy3K** [comment]
I have too much happening at then moment to be able to follow up on this, so I'll close the ticket for now. Thank you though!
