### ISSUE TITLE
Windows Defender tags PCHunter as a CoinMiner

### ISSUE THREAD

**Issue by P3t3rU5** [bmrf/tron#178]
Windows Defender is tagging PCHunter as a CoinMiner

https://i.imgur.com/iCXuiFF.png

Cheers

**Comment by dr-raypc** [comment]
this is a Microsoft issue. false positive 

Sent via Dr. Ray mobile

**Comment by vocatus** [comment]
Thanks for letting us know, but @dr-raypc is right, it's an MS issue, not much we can do about it other than just mark it as a false positive.
