### ISSUE TITLE
Suggestion: zip the logs

### ISSUE THREAD

**Issue by borekon** [bmrf/tron#181]
Hi, i'm going to create a custom script to zip the logs (using command-line 7z.exe) and upload via webdav using command-line function of winscp.
It would be great you add this function to the sending email feature because most of the logs are bigger than 25 Mb and the eamils are not delivered.
Thanks!

**Comment by vocatus** [comment]
Hi @borekon , the logs are greater than 25 MB?? Can you zip one and email it to me for an example? I'm surprised to hear of that size, most of the time `tron.log` is 1 MB or less.

**Comment by borekon** [comment]
TBH, no the tron.log itself, but the _tron_removed_files.txt_
Below is a random mail sent with your script
![image](https://user-images.githubusercontent.com/9289539/87390563-6271ee00-c5a9-11ea-92da-1a2bbe9c055c.png)
