### ISSUE TITLE
Suggestion to add a block for MS bloatware installation

### ISSUE THREAD

**Issue by refeaime** [bmrf/tron#183]
Hi!
Your tool does a pretty good job on removing different kind of bloatware from different companies, that is great. For the most apps it is once nd for all. At least for a really long time. 
But when it comes to the WIndows updates... It always installs back those unwelcome applications. 

They can be removed with your tool, can be removed manually... But damn! Maybe there is a way to put some kind of blocker to that kind of stuff?

**Comment by vocatus** [comment]
Unfortunately there isn't :/ When MS pushes new updates, it frequently silently loads back a bunch of bloat, with no way to prevent it.

**Comment by refeaime** [comment]
Are you sure? Windows got an internal restrinction based on signed signed certificate thus it might be used as filter for that kind of software. 
This might not be an option if MS is a publisher.

**Comment by dennyamarojr** [comment]
Have Deprovisioned regedit to prevent the apps to reinstall 
Source: https://docs.microsoft.com/en-us/windows/application-management/remove-provisioned-apps-during-update
