### ISSUE TITLE
metro_Microsoft_modern_apps_to_target_by_name.ps1 doesnt actually work

### ISSUE THREAD

**Issue by journeym** [bmrf/tron#187]
This script plainly doesn't work.
First off, the variables are completely screwed, and the structure is written so that script skips duplicates and needs more then one run to remove all appx.
I don't see any quick way to fix it, but for my purposes i had to rewrite practically everything to make it work in one run.

**Comment by vocatus** [comment]
The script has worked well on thousands of systems without issue, closing closing out.

**Comment by journeym** [comment]
well, this is just another fake instrument, written by ppl who obviously don’t know what the hell they are doing. Great.
