### ISSUE TITLE
av detection

### ISSUE THREAD

**Issue by Wendys-corp** [bmrf/tron#189]
Kaspersky's system watcher kills and deletes tron and rolls back actions done
i have to disable my av to get it to start working

suggestion for this disable anti virus while to script is running
the av gos off at this stage and area
 Launch job 'Purge oldest Shadow Copy set (Win7 and up)'...
 as soon as it tries to purge Kaspersky's system watcher kills and deletes tron and rolls back actions done

**Comment by vocatus** [comment]
Hi @Wendys-corp , in the instructions this is covered. It says to disable ALL anti-virus software _before_ running Tron.

**Comment by BusterBrawls** [comment]
I believe you can set aN AV exception for Tron, which would be preferable to disabling AV all together. The instructions vary by AV vendor.
