### ISSUE TITLE
Commit messages

### ISSUE THREAD

**Issue by nemchik** [bmrf/tron#19]
This is really the same as https://github.com/pplude/TronScriptEvo/issues/4 but to sum it up, please be more specific with the commit messages. Trying to find when something changed is MUCH harder when commit messages only show the version number.

**Comment by nemchik** [comment]
Also using the same commit message for more then one commit makes it even harder. Ex 3 commits all messaged "6.5.2"

**Comment by nemchik** [comment]
Furthering my last comment (because it's late and my thoughts are incomplete)
If I were to ask someone what version they were using and they replied 6.5.2 I would then have to ask "which 6.5.2?" Because there are 3 commits of 6.5.2, and any of those changes could make a difference in the behavior being seen. Looking back at 6.5.0 makes this issue even more evident.

I do still encourage you to make a commit with a version number when you have decided to "officially release" a new version, because then you can see easily in the commit history when each version happened, and the names of the commits in between each version.

Generally to make things easy for others to follow along and contribute, it's a good idea to keep one idea per commit, and the commit message should explain what the idea is doing. One idea could change multiple files. But you should avoid multiple ideas in a single commit if possible. When releasing a new version, change the version number that is hard coded in the file, and commit that change with the version number as the commit message. Don't include actual code changes in version bump commits.

This is all just me making recommendations in hopes of making your project easier for contributors to participate. If this doesn't work for you, please ignore me and continue making your awesome script in whatever way works best for you. Thank you, I will definitely be making use of your script personally, and probably parts of it at work :)

**Comment by vocatus** [comment]
Hi nemchik,

I sort of assumed no one watches the github, and I do all development on my local workstation, just pasting it to GH when it's done. I'll try to throw more information in commit messages but no promises! 

The reasoning behind version numbers in the commit message was that usually a v6.5.2-testing indicates I'm still fiddling with it, while a v6.5.2 indicates it's "done." But then when a bug crops up and I have to fix it, I just update the code and leave the same version number in the commit message because it's still the same release. How would you suggest notating bug fixes? In the extended comments field?

**Comment by nemchik** [comment]
My mentality is that if you fix a bug that counts as a change, and that change would be included in the change log, and any change since the last release should be included in the next release.

This all comes down to how you would like to use the version number. Here are two web pages (google results) with information about making use of version numbers
http://stackoverflow.com/questions/65718/what-do-the-numbers-in-a-version-typically-represent-i-e-v1-9-0-1
https://en.wikipedia.org/wiki/Software_versioning
On the StackOverflow page the accepted answer indicates that one of the most common version numbering structures is Major.Minor.BugFix.BuildNumber
So really it's up to you how you'd like to manage the version numbering, but if it were me doing it I would increase the version number for any release, and bugfixes would happen between releases. If a bug is fixed and not yet released then the general public (non git users) would have to wait until that bugfix is included in the next release. You can choose to make releases as often or infrequent as you like based on how often you fix a bug, test, and then release a new version.

Again all of this is entirely up to your preference, so please don't let me hold you back from doing whatever is comfortable for you. I'm posting this in hopes of you making the project more contributor friendly on git. Accomplishing this would allow others to see the upcoming changes, test them out, provide feedback, and then you can decide to release a new version when you feel it's ready based on your testing and feedback from contributors.

**Comment by nemchik** [comment]
I guess as a side note, I consider what you're currently doing "backporting", meaning to include a bugfix from a newer release into an older version of the software. So rather than releasing a new version (like 6.5.3 or 6.5.2.2) you are backporting the fixes into 6.5.2 and re-releasing it. IMO this makes it difficult to truly keep track of what version one of your users is making use of. This could cause undue headaches for you in the future.

Also you mentioned you made a commit at 6.5.2-testing but I see only one of those, while I see multiple commits as 6.5.2, which implies you had made multiple changes to the released version of 6.5.2 after it was released.

Generally what i have seen most git repos do is to make changes and bugfixes and then once everything for a new release is ready change the hard coded version number in the file and commit that with the version number as the message. So an example would be this

6.5.2
bugfix zc
bugfix zb
bugfix za
6.5.1
bugfix yc
bugfix yb
bugfix ya

So I would not expect bugfix za to be included in 6.5.1

**Comment by vocatus** [comment]
If you look at the included changelog, you'll see this is how I version things:

    Legend:
     + Addition   - Removal  * Update/improvement
     . No change  ! Bug fix  / Change (non bug-fix)

    Version number legend:
      x.x.x
      | | |
      | | program/definition update, minor change or bugfix (critical or regular)
      | regular release or feature change
      major release or feature change

I don't count tiny alterations as new versions (e.g. changing the text of a string, editing a comment, etc), but I can throw an `-rcN` designator on the end, where N is release candidate. 

Tron's versioning is based off the [Semantic Versioning](http://semver.org/) standard.

Part of the difficulty with Tron is that it's not purely a source project as there are many tools it relies on that I don't control. So if a new version of ComboFix comes out, and it's included, but Tron didn't change, does that mean Tron is on a new version? 

For now I'm not going to change versioning standards or build separate alpha/beta/testing/etc releases, I just don't have time for it. However, I do appreciate your comments, and will try to be more descriptive with version numbers, as well as pay closer attention to properly incrementing version numbers when pushing bug fixes, minor releases, etc. A while ago I was incrementing the third digit with every bug fix that went out, but sort of drifted out of doing it, so thanks for the reminder. 

I'll close this for now, thanks for the feedback.

**Comment by nemchik** [comment]
Maybe this could work?
```
  x.x.x.x
  | | | |
  | | | external tool update
  | | program/definition update, minor change or bugfix (critical or regular)
  | regular release or feature change
  major release or feature change
```
I guess really where i'm going with this though is that until you actually release a new version to the public, the changes in between releases would be committed to git with a commit message indicating what the change is doing. Then when you have decided a release is ready for the public commit a version number as the commit message, but try to keep version number commits to only changing the hard coded version number in the bat file (and maybe adding the changelog). This way the changes are all in their own commits, and the versions are kind of like mini-milestones.

Anyway, cheers!
