### ISSUE TITLE
Dont delete.... please rename... or backup the deleted file...

### ISSUE THREAD

**Issue by Blazzycrafter** [bmrf/tron#192]
Dont delete.... please rename... or backup the deleted file...

i wanted too re enable telemetry in W11 but i see in https://github.com/bmrf/tron/blob/40c1c08b3efd9f51e136266ca576c801b37a19aa/resources/stage_4_repair/disable_windows_telemetry/purge_windows_10_telemetry.bat#L208 

You deleting a entire service "RetailDemo"

maybe dont delete this... rename or make a backup

**Comment by Zusier** [comment]
adding `-str` should skip removal of that

See [here](https://github.com/bmrf/tron#command-line-use)

**Comment by vocatus** [comment]
Hi @Blazzycrafter , that service is unnecessary on a Windows system that isn't a retail demo unit in a store. @Zusier 's comment regarding the use of the `-str`  switch will preserve that service if you REALLY want it.
