### ISSUE TITLE
Does anyone know if  TronScript disables Heartbeat Telemetry of "Microsoft Windows Malicious Software Removal Tool " ?

### ISSUE THREAD

**Issue by abu-101** [bmrf/tron#193]
Does anyone know if  TronScript disables Heartbeat Telemetry of "Microsoft Windows Malicious Software Removal Tool "...Malwarebytes found two infected registry keys(Potentially Unwanted Modification (PUM) that was modifite..
I want to know If Tronscript changed it(than its okay), 
but if not it was a virus right?
Registry path was First:
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Policies\Microsoft\MRT\DONTREPORTINFECTIONINFORMATION
Second path:
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\MRT\DONTREPORTINFECTIONINFORMATION

**Comment by NickDeBeenAIE** [comment]
Those 2 registry edits are unwanted, as they slowly brick your entire system over time as this has happened to me once.

I had to completely re-install Windows 10 at the time.

So does O 'N' O Shutup 10 as it completely disables the ability to update your PC.

**Comment by abu-101** [comment]
> 
> 
> Those 2 registry edits are unwanted, as they slowly brick your entire system over time as this has happened to me once.
> 
> I had to completely re-install Windows 10 at the time.
> 
> So does O 'N' O Shutup 10 as it completely disables the ability to update your PC.

I am using O&O ShutUp10 but only recommended settings...  
It is not worth to mess up with windows update. I agree...

**Comment by vocatus** [comment]
Tron does not disable Windows Update, nor does it use O&OShutup10's ability to disable it. It also does not disable MSRT.
