### ISSUE TITLE
Error: 4001

### ISSUE THREAD

**Issue by NickDeBeenAIE** [bmrf/tron#194]
ERROR:4001 UNABLE TO REPAIR WMI, ATTEMPTS:3 (3:4001).

Is this normal?

If not, then I advise an update to the code that skips this as Windows WMI is Windows Server 2021 related, and no Windows 10 or 11 installation on a Desktop PC has this.

**Comment by paroxy777** [comment]
WMI has been included with, and grows with, every release of Windows since NT 4.  Services.msc shows me Windows Management Instrumentation is running.

Malware or another software / hardware issue has broken WMI. I would suggest a backing up and reinstalling Windows.

**Comment by NickDeBeenAIE** [comment]
Ok, well I always leave nothing important behind.

**Comment by NickDeBeenAIE** [comment]
So I just went ahead and reinstalled Windows 11 Pro.

**Comment by NickDeBeenAIE** [comment]
To be honest, there should be a way to stop Windows 11 from being delivered to anyones PC's, its pretty bad and way too unstable.

**Comment by vocatus** [comment]
If Tron can't repair WMI, I agree, it's best to re-install Windows at this point.
