### ISSUE TITLE
Kaspersky is now blacklisted due to national security

### ISSUE THREAD

**Issue by cloud3ater** [bmrf/tron#198]
I noticed tronscript is using tdss killer. Kaspersky is now on the blacklist by fcc so may want to reconsider using it.

**Comment by vocatus** [comment]
This has come up before (in...2018 I think?) but as the tool hasn't changed in a number of years, outside of definition updates, I'm leaving it in for now. Am currently looking at candidate replacements however, and will remove TDSSK when one is selected.
