### ISSUE TITLE
Skip switching off the telemetry

### ISSUE THREAD

**Issue by kolosovpetro** [bmrf/tron#199]
As I see, tron has a flag `-str` that skips telemetry removal (just turn telemetry off instead of removing it)

Can you add a flag that preserve not even disabling of the telemetry? So that telemetry won't be even touched.

Personally I use telemetry to control the location and state of all my devices, so I need it

Thanks

**Comment by vocatus** [comment]
I'm going to leave it as-is for now but you can safely delete or comment out the telemetry disabling section of the code prior to running and it won't affect other script functions.
