### ISSUE TITLE
Have Tron download tools?

### ISSUE THREAD

**Issue by nemchik** [bmrf/tron#20]
Would it be possible to have Tron download the external tools that it uses, rather than packaging them together with the bat files?

**Comment by vocatus** [comment]
Frequently asked, [see here](https://www.reddit.com/r/TronScript/wiki/index#wiki_2._why_don.27t_you_use_ninite_or_ketarin.3F_.2F.2F_tron_is_too_big)

**Comment by nemchik** [comment]
The closest pre-existing thing I can think would be something like  chocolatey.org but I don't think all the tools are available. Also involving something like chocolatey assumes that all machines support it (requires power shell), and the same would apply to pretty much anything that isn't custom built. I think building something specifically for tron would end up relying on either wget or curl, or possibly btsync, so those would be the minimum required to include.

In theory this is a neat goal for the project, but after a lot of thought I agree mostly with your FAQ note that the current setup is standalone and can be used offline. Having any kind of tools download would require you to maintain at least two versions of tron, one that downloads as needed, and the other that includes the tools and maybe downloads updates as needed (when a network connection is available, and if this behaviour is accepted by the user running from).

For now I'll close this issue, but I'll definitely help out if I think of something that might work for this.

**Comment by vocatus** [comment]
Yeah, I like your thoughts on it. I kind of ended up at the standalone method after thinking for quite a while on it. 

One *possible* option I thought of was to bundle the utilities like we're doing currently, then automatically try to grab the latest versions at launch based on the use of a flag (or use a flag to NOT try to get new versions). The problem I came to was back to the downloader code - I'd have to maintain an update script when various URL's change. Of course, it could failback to the individual local copy of whatever tool it couldn't find, but that's a decent-size undertaking to build.

If you want to build an update script that will handle failing back to the internal version of a tool and can put it together as a sub-script that Tron calls, I could test integrating it. It really would be ideal, especially for those times when I'm away for an extended period and can't push out a refresh release with the latest versions of everything.

**Comment by nemchik** [comment]
I like the mentality of having the tools able to update and having the flag for it, and i agree if you're unavailable this would keep things a little more current and reduce the work you have to do to keep things updated between releases. If I can come up with some time and an idea about how to make something like this possible I'll certainly bring it to you. I will say don't hold your breath though because I don't consider myself nearly the level of guru that you are with putting together batch files (thus tron! ty!) but if there is something I can do and I find the time then I'll do what I can.

**Comment by vocatus** [comment]
Sounds good
