### ISSUE TITLE
Add reg key to Purge win 10 tel ?

### ISSUE THREAD

**Issue by Starmania** [bmrf/tron#200]
Hey,
I found a key that seemes to resemble to this key : https://github.com/bmrf/tron/blob/dd695c4d70da7a61fcf274defb45e27294d3a60f/resources/stage_4_repair/disable_windows_telemetry/purge_windows_10_telemetry.bat#L280

It is a totally different process or just an another name for telemetry ?

The key in question: `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\WMI\Autologger\Diagtrack-Listener`

![image](https://user-images.githubusercontent.com/52313983/166249610-65764529-c1ef-4e4d-b506-ab5145f84849.png)

**Comment by NickDeBeenAIE** [comment]
You can actually go into onoshutup10.tron.cfg and disable everything there, and yes, you can also go into the registry and delete the 2 registry items that tron makes and places in the registry.

They prevent the operating system from stabilising on boot.

Therefore you'll get more BSOD's.

**Comment by Starmania** [comment]
No, Tron has set the `Start` key to `0`, and I found a key similar to the one Tron disables, and I want to know if Tron should also disable this key...

**Comment by vocatus** [comment]
Hi @Starmania , apologies for the slow reply. You're right, that's an additional key that Tron needs to set. I've updated the script and it will go out in Tron v12.0.4 (releasing today). Thanks.

**Comment by Starmania** [comment]
Good !

**Comment by Starmania** [comment]
And question, why no update for 6 month ?
