### ISSUE TITLE
Attempt junkware removal: Phase 3 (wildcard by name) taking a few days

### ISSUE THREAD

**Issue by Donovoi** [bmrf/tron#202]
Hi

I'm using tron on my desktop (nvme m.2, i9 7900X aurous gaming 9 mobo)

and junkware removal phase 3 has been running since 2022-07-04 18:21:48.23 

and it is still not finished. Last time I ran Tron (2 months ago), it got to this stage and took about 3 days before I cancelled it and reimaged my computer. 

Is there something I need to set or something I should be doing to ensure it only takes a few hours as stated in the Readme?

Let me know what you think :)

**Comment by vocatus** [comment]
You can safely comment out the portion of the Stage 3 script that calls the "wildcard by name" section and re-run Tron. It will skip over that portion.
