### ISSUE TITLE
CCleaner bad

### ISSUE THREAD

**Issue by rktfier** [bmrf/tron#207]
A lot of the time people on the forums or the internet tend to tell that cleaning software such as CCleaner, AdvSystemCarre etc. usually does more damage to the computer as it does good, which i have been able to experience a few years ago and proceeded to never use them again. Just typing "ccleaner bad" into DDG results in a ton of webpages claiming that it can mess up your system if used wrongly, which i agree. When i look around the script i see some whitelists about it but i just wanted to make sure that the developers are aware of it, and other people like me don't just turn it down because of it.

**Comment by vocatus** [comment]
The exclusions and whitelists in Tron have been developed heavily over the last seven or so years. CCLeaner is safe to use.
