### ISSUE TITLE
Disable create desktop icon for malwarebytes

### ISSUE THREAD

**Issue by numdouglas** [bmrf/tron#208]
During disinfect stage, the Malwarebytes installer will default to creating a desktop icon after installing. This will rearrange my desktop icons. It will then be uninstalled after this step is complete, meaning I now have re-arranged icons and a gaping hole where one used to be. It's a minor issue but can be quite an annoyance, I would appreciate it if any preflight commands to disable creation of desktop icon were used before installing MB.

**Comment by vocatus** [comment]
[Added](https://github.com/bmrf/tron/blob/master/resources/stage_3_disinfect/stage_3_disinfect.bat#L5), thanks for reporting. Will go out in the next version.
