### ISSUE TITLE
how to whitelist software after using tron

### ISSUE THREAD

**Issue by jenkshi** [bmrf/tron#209]
Hi, I have an Asus laptop that uses software from the manufacturer called ArmouryCrate. It will allow me to overclock or even turn off the GPU when I take my laptop away. I used Tron since I had an issue and thankfully Tron solved it, but the ArmouryCrate was uninstalled, and even when I was trying to install it, the process would not complete and will stay like the image attached. 

Please help me.
![image](https://user-images.githubusercontent.com/47603870/200344960-2d3d29ed-bf0a-4138-a6ab-a5ff46a78edc.png)

**Comment by TheScreechingBagel** [comment]
not a tron issue, tron doesn't blocklist anything after it runs

**Comment by jenkshi** [comment]
I even have wifi issues after running tron I might format my laptop to get fix it

**Comment by vocatus** [comment]
Tron doesn't blacklist anything after its done running. If you want to exclude it from removal DURING a Tron run, this is covered in the instructions (look specifically at the Stage 2 lists of what it targets for removal).
