### ISSUE TITLE
the disinfection step does not work on windows 11 arm

### ISSUE THREAD

**Issue by Bitbitti** [bmrf/tron#211]
sophos says it cannot load the engine
kvr does not start at all

**Comment by vocatus** [comment]
Hi @Bitbitti , what subversion of win11 are you on? (start --> run --> winver). e.g. 22h2

**Comment by Bitbitti** [comment]
hi, version 22h2 build os 22621.1848

**Comment by vocatus** [comment]
Hi @Bitbitti, many of the tools Tron uses are x86 / x86_64 only, and do not have ARM versions available.
