### ISSUE TITLE
CCleaner tasks on Task Scheduler after running the script.

### ISSUE THREAD

**Issue by rktfier** [bmrf/tron#212]
![image](https://user-images.githubusercontent.com/75695425/213915286-304d502c-7737-4dd1-a262-cf0dc47bbbfc.png)

The script is run on a fresh install, with no errors.

**Comment by vocatus** [comment]
Added code to delete `CCleanerCrashReporting` task. We can't delete the user-specific task as I've been unable to find a good solution for taskmgr wildcard deletion. Thanks for reporting, it'll go out in next release.
