### ISSUE TITLE
Windows Terminal (wt.exe) not whitelisted by default

### ISSUE THREAD

**Issue by ernest859** [bmrf/tron#213]
**Issue**: on Windows 11, the default command line is now Windows Terminal (wt.exe). If you launch tron.bat from Windows Terminal (i.e you want to use command line switches "tron.bat -a -x -r"), Windows Terminal closes (and thus stops tron.bat) during the job "ProcessKiller".

**Fix**: add wt.exe to the tron/resources/stage_0_prep/processkiller/whitelist.txt

I know this is an easy fix on the user side, however I think this should be in the default whitelist, as Microsoft has made Windows Terminal the default cli for right click context menu and also for right clicking the start button, thus, this will potentially be one of the preferred ways for admins to run Tron when more users adopt Windows 11.

**Comment by TylersComputersKC** [comment]
[https://github.com/bmrf/tron/pull/215](url)

**Comment by vocatus** [comment]
Thanks @TylersComputersKC , will add to the whitelist. What is the full path to the exe? I checked on my test VMs and couldn't find it. System32?
