### ISSUE TITLE
Reddit download

### ISSUE THREAD

**Issue by Deobot2** [bmrf/tron#218]
it isn't a code issue but I don't really have anywhere else to post this, because of "Lovely" reddit policy's I am unable to get the download for tron.  I don't know if there is a separate download but all of the downloads I found linked to the reddit dead end.

**Comment by 2231puppy** [comment]
For now, use the Wayback Machine:
https://web.archive.org/web/20230530032009/https://old.reddit.com/r/TronScript/comments/10rucm2/tron_v1205_20230202_revert_ccleaner_to_fix_cookie/

**Comment by TiJof** [comment]
here is a (official ? probably) link : https://bmrf.org/repos/tron/

**Comment by borekon** [comment]
You could maybe put the magnet link somewhere around here

**Comment by NextGenOP** [comment]
You can use https://nutbread.github.io/t2m/ to get the magnet link

**Comment by borekon** [comment]
I know, but is the torrent file on this repo?
________________________________
De: NextGenOP ***@***.***>
Enviado: sábado, 17 de junio de 2023 2:11
Para: bmrf/tron ***@***.***>
Cc: Alfonso ***@***.***>; Comment ***@***.***>
Asunto: Re: [bmrf/tron] Reddit download (Issue #218)


You can use https://nutbread.github.io/t2m/ to get the magnet link

**Comment by Settyness** [comment]
> DO NOT DOWNLOAD TRON FROM GITHUB, IT WILL NOT WORK!! YOU NEED THE ENTIRE PACKAGE FROM [r/TronScript](https://old.reddit.com/r/TronScript)

As capable as people have become of acknowledging the evils of reddit, I hope they too can recognize the importance of not putting one's eggs in one basket.

**Comment by borekon** [comment]
> You could maybe put the magnet link somewhere around here

magnet:?xt=urn:btih:1cde34feea62d9da68106cea3ee958cb06c85148&dn=Tron%20v12.0.5%20%282023-02-02%29

**Comment by diaverso** [comment]
Tron v12.0.5 (2023-02-02)
https://1fichier.com/?u8cfeqgz3onpdwlrlirt

**Comment by vocatus** [comment]
Tron is always available via torrent and the main sub is open again.
