### ISSUE TITLE
PC wont turn Off after Running TRON

### ISSUE THREAD

**Issue by jrigle** [bmrf/tron#224]
After running Tron, my PC is unable to power off normally. Instead, I have to use the power button to shut it down. Even when attempting to shut down via the desktop, the screen displays the 'shutting down' message, the monitor goes blank with no signal, but the PC components remain powered on, excluding the monitor, mouse, and keyboard. I attempted to use a restore point, but it was unsuccessful. 
any solution?

**Comment by vocatus** [comment]
Hi @jrigle , were you able to find a solution to this? My guess is visiting the power settings menu in Windows will allow you to resolve it. Tron resets power settings to default (by default), although this can be skipped with a command-line switch.

**Comment by vocatus** [comment]
Closing due to no response.
