### ISSUE TITLE
Windows Defender detects copied TronScript as adware

### ISSUE THREAD

**Issue by Inkertus** [bmrf/tron#228]
Whenever backing up TronScript from A to B Win. Def. flags the file as adware. I imagine this to be a false positive due to either an included .exe that has bundled software or because the script runs loads of .exe files in sequence (which adware also does).

**Comment by vocatus** [comment]
This is covered in the Wiki and the instructions, it's a false positive. To work around this mark Tron or the folder it's in as safe/excluded.
