### ISSUE TITLE
Launches Malwarebytes but doesn't start scan

### ISSUE THREAD

**Issue by javproj** [bmrf/tron#3]
Not sure if this is an issue or a limitation. If it's an issue (close otherwise):
Stage 2 launches MWB, but does not start scanning. The CMD window shows that it's starting MWB, then says Done immediately after launching and moves on.

Running Tron 3.5 (4 hours in) on a bitcoin-mining rootkit (nasty) infected computer (Win 7 Enterprise).

**Comment by nemchik** [comment]
@vocatus would it make more sense to consider MBAM a stage 8 manual tool? sure it can be installed automatically, but if the whole process cannot be automated doesn't it make more sense to be considered manual?

**Comment by vocatus** [comment]
@nemchik, not for now, [see discussion here](https://www.reddit.com/r/TronScript/comments/3hz9k4/three_question_poll_and_tron_development_comments/cuho145).
