### ISSUE TITLE
About Whitelist

### ISSUE THREAD

**Issue by PFCKrutonium** [bmrf/tron#37]
https://www.reddit.com/r/TronScript/comments/3oabz2/please_whitelist_ebay_blackthorne_on_debloat/

Would you like it if I added a whitelist option to my quick removal application?

**Comment by spexdi** [comment]
I think if it's easy to add I don't see a harm, though IMHO it doesn't sound like it would be a huge feature, as commenting out the line, or tweaking the blacklist may be easer (IE: "eBay W*")

**Comment by PFCKrutonium** [comment]
I think I will leave it out then.

**Comment by vocatus** [comment]
I'm going to close this out then, thanks.
