### ISSUE TITLE
Issues with a couple ccleaner.ini settings

### ISSUE THREAD

**Issue by spexdi** [bmrf/tron#42]
Line 24: (App)Hotfix Uninstallers=True will bake in windows updates, creating similar situation to Issue #35 .

Line 32: WipeFreeSpaceDrives=C:\ removes Restore Points (http://forum.piriform.com/index.php?showtopic=38712&p=235275)

Line 41: AutoClose=0 maybe we can change value to 1?

Line 42: BackupPrompt=1 maybe we can change value to 0?

**Comment by vocatus** [comment]
Fixed, thanks.

Wipe free space was not enabled so that won't have any effect.
