### ISSUE TITLE
tron.bat calls block_windows_updates.vbs, but the file is actually called hide_windows_updates.vbs

### ISSUE THREAD

**Issue by waregen** [bmrf/tron#45]

**Comment by zp** [comment]
the file **resources/stage_4_repair/purge_windows_telemetry/purge_windows_10_telemetry.bat** also calls **block_windows_updates.vbs**

**Comment by vocatus** [comment]
I'll get this fixed, thanks. Good find.

**Comment by vocatus** [comment]
Fixed
