### ISSUE TITLE
Tron doesn't detect SSD on my XPS 13 9350

### ISSUE THREAD

**Issue by isaactsg** [bmrf/tron#59]
When I run tron it says that it hasn't detected my SSD and so runs defrag. My XPS 13 has a 256GB Samsung M.2 PCIe SSD

**Comment by RB14060** [comment]
To help troubleshoot, please do the following:

Open a command prompt as an administrator and navigate to your Tron folder, then to `tron\resources\stage_6_optimize\defrag\` If you don't know how to do these then a quick Google search can help you out. Inside the command prompt, run the following:

`smartctl --scan`

Afterwords, for each entry, run

`smartctl <path> -a`

For example, here's my output:

`E:\Users\Ryan\Desktop\Tron-YT\tron\resources\stage_6_optimize\defrag>smartctl --scan`
`/dev/sda -d ata # /dev/sda, ATA device`
`/dev/sdb -d ata # /dev/sdb, ATA device`
`/dev/sdc -d ata # /dev/sdc, ATA device`

I would then run

`smartctl /dev/sda -a`
`smartctl /dev/sdb -a`
`smartctl /dev/sdc -a`

The line we're looking for is one called Rotation Rate, and it should be near the top of the output. For each device you test, please provide the Rotation Rate line. It's possible that smartctl either doesn't see it as a Solid State Drive, or it outputs something else that Tron doesn't recognize as being an SSD. If you need help with any of this, I'm available on the Tron IRC channel, via PM here, or on reddit at /u/RB14060.

**Comment by isaactsg** [comment]
I ran the commands, here's the output:

C:\Users\Isaac\Downloads\tron\resources\stage_6_optimize\defrag>smartctl /dev/sda -a
smartctl 6.4 2015-06-04 r4109 [i686-w64-mingw32-win8(64)] (sf-6.4-1)
Copyright (C) 2002-15, Bruce Allen, Christian Franke, www.smartmontools.org

Read Device Identity failed: Input/output error

A mandatory SMART command failed: exiting. To continue, add one or more '-T permissive' options.

I also added -T permissive option and here is what I got:

C:\Users\Isaac\Downloads\tron\resources\stage_6_optimize\defrag>smartctl /dev/sda -a -T permissive                      smartctl 6.4 2015-06-04 r4109 [i686-w64-mingw32-win8(64)] (sf-6.4-1)                                                    Copyright (C) 2002-15, Bruce Allen, Christian Franke, www.smartmontools.org                                                                                                                                                                     Read Device Identity failed: Input/output error                                                                                                                                                                                                 === START OF INFORMATION SECTION ===                                                                                    Device Model:     [No Information Found]
Serial Number:    [No Information Found]
Firmware Version: [No Information Found]
Device is:        Not in smartctl database [for details use: -P showall]
ATA Version is:   [No Information Found]
Local Time is:    Mon Dec 21 22:44:52 2015 EST                                                                          SMART support is: Ambiguous - ATA IDENTIFY DEVICE words 82-83 don't show if SMART supported.
SMART support is: Ambiguous - ATA IDENTIFY DEVICE words 85-87 don't show if SMART is enabled.
A mandatory SMART command failed: exiting. To continue, add one or more '-T permissive' options.

**Comment by RB14060** [comment]
Did you open Command Prompt as an Administrator or as a regular user? Just opening it while being signed in as an Administrator won't work, you have to explicitly tell it to run as one.

**Comment by isaactsg** [comment]
Yes I did run as admin:
![image](https://cloud.githubusercontent.com/assets/10574297/11947504/de615f64-a835-11e5-8dcd-52ca8c0bd56b.png)

**Comment by RB14060** [comment]
Gotcha, just making sure. Looks like your device doesn't correctly present information about itself which prevents SSD detection from working properly. I'll change some code around and submit a pull request to get this fixed in the next release. Thanks for the bug find!

**Comment by isaactsg** [comment]
Thanks!

**Comment by vocatus** [comment]
Closing this as resolved due to implementation of PR #60 . Thanks for the report.
