### ISSUE TITLE
Consider syntax redirection in place of ERRORLEVEL

### ISSUE THREAD

**Issue by nemchik** [bmrf/tron#61]
Reference: http://ss64.com/nt/syntax-redirection.html
Example: https://github.com/bmrf/tron/pull/56/files#diff-bc58a3877fd21a346ef229f4f6d0328fL209

It might be a good idea to avoid issues like [this](https://github.com/bmrf/tron/pull/58).

I've started this as an issue for discussion before putting the work into making all the changes. I don't mind doing it, but I'd like to know if anyone else has any input.

**Comment by vocatus** [comment]
Commented on original PR
https://github.com/bmrf/tron/pull/58
