### ISSUE TITLE
Defraggler with df.exe

### ISSUE THREAD

**Issue by nemchik** [bmrf/tron#62]
Based on [this article](https://www.piriform.com/docs/defraggler/advanced-usage/command-line-parameters) defraggler should be run using df.exe, not defraggler.exe. I can make a PR to correct this, but I wanted to open it up to discussion in case anyone else has more experience with this tool and maybe I'm missing something.

I have tested Tron's syntax and all it does is open the Defraggler interface, but replacing defraggler.exe with df.exe and including the same command line switches seems to work just fine.

**Comment by vocatus** [comment]
I *think* (I'll double-check) the bundled `defraggler.exe` is actually just a renamed `df.exe`, to make it clear to users what the .exe is for.

**Comment by nemchik** [comment]
If you're using the portable zip download from the Piriform site this would include a separate df.exe (and df64.exe). This also kind of brings up the point that it might be a good idea to have Tron detect 64-bit architecture and use the appropriate tools when available.

**Comment by vocatus** [comment]
I'm not sure a 64-bit Defraggler binary would make any real-world difference. I believe I purposefully left it out since it doesn't grant any performance increase. Generally I try to only include 64-bit binaries if there might be some functional reason

**Comment by vocatus** [comment]
Verified `defraggler.exe` is indeed a renamed `df.exe`. Closing.
