### ISSUE TITLE
Windows Installer does not work in Safe Mode, so OEM debloat fails

### ISSUE THREAD

**Issue by Verteiron** [bmrf/tron#67]
Following the procedure outlined [here](http://www.thewindowsclub.com/make-windows-installer-work-in-safe-mode) allows Tron to uninstall things as expected under Safe Mode/Safe Mode with Networking. Otherwise uninstallation fails on the vast majority of items that would otherwise be removed.

Tested on two HP Elitebooks running Windows 7 and a Toshiba laptop running Windows 10, problem occurred in all three cases.

I think adding
```
REG ADD "HKLM\SYSTEM\CurrentControlSet\Control\SafeBoot\Minimal\MSIServer" /VE /T REG_SZ /F /D "Service"

REG ADD "HKLM\SYSTEM\CurrentControlSet\Control\SafeBoot\Network\MSIServer" /VE /T REG_SZ /F /D "Service"
```

somewhere in Stage0, or in Stage2 prior to calling the debloat scripts would probably resolve this.

**Comment by vocatus** [comment]
Really good find. I'd force started the `AppXSvc` service to allow removal of Metro apps, but somehow missed doing the same for the MSIServer. I think it was in the code a while ago and must've gotten accidentally removed at some point. Thanks Verteiron.
