### ISSUE TITLE
Additions for local tracking and other Windows automation

### ISSUE THREAD

**Issue by Itsnothectic** [bmrf/tron#85]
Let me know if its okay for me to add the info here,
I dont know a scripting language well enough to contribute code but I can say for example something like an evironmental variable 

devmgr_show_nonpresent_devices=1

Should be added in System properties under System variables. This shows extra things in Device Manager including potentially old rootkits or if someone has plugged in and removed a USB.

If its okay I have a good amount of info to add but just not in code form.

**Comment by vocatus** [comment]
Hi Itsnothectic, 

If you want to email your suggestions to me that might be better. You will need to be specific about what you did and exactly how you accomplished it (list of steps, etc). I'll close this ticket and wait for an email from you. My email is in the Tron instructions file.
